-- MySQL Script generated by MySQL Workbench
-- Thu Feb 22 12:27:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library_fp
-- -----------------------------------------------------
DROP schema IF EXISTS library_fp;
DROP schema IF EXISTS mydb;
CREATE SCHEMA IF NOT EXISTS `library_fp` DEFAULT CHARACTER SET utf8 ;
USE `library_fp` ;

-- -----------------------------------------------------
-- Table `library_fp`.`Borrowers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_fp`.`Borrowers` ;

CREATE TABLE IF NOT EXISTS `library_fp`.`Borrowers` (
  `Borrower_id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `street_address` VARCHAR(45) NULL,
  `amount_due` DECIMAL(5,2) NULL DEFAULT '0.0',
  CONSTRAINT borrowers_pk PRIMARY KEY (`Borrower_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_fp`.`Librarians`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_fp`.`Librarians` ;

CREATE TABLE IF NOT EXISTS `library_fp`.`Librarians` (
   `LibrarianID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `street_address` VARCHAR(45) NULL,
  CONSTRAINT librarians_pk PRIMARY KEY (`LibrarianID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_fp`.`Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_fp`.`Books` ;

CREATE TABLE IF NOT EXISTS `library_fp`.`Books` (
  `ISBN` CHAR(13) NOT NULL,
  `book_title` VARCHAR(45) NOT NULL,
  `Publication_Year` INT NULL,
  CONSTRAINT books_pk PRIMARY KEY (`ISBN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_fp`.`Barcodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_fp`.`Barcodes` ;

CREATE TABLE IF NOT EXISTS `library_fp`.`Barcodes` (
  `barcode` INT NOT NULL,
  `ISBN` CHAR(13) NULL,
  CONSTRAINT barcodes_pk PRIMARY KEY (`barcode`),
  UNIQUE INDEX `barcode_UNIQUE` (`barcode` ASC),
  INDEX `ISBN_idx` (`ISBN` ASC),
  CONSTRAINT isbn_fk_1
    FOREIGN KEY (`ISBN`)
    REFERENCES `library_fp`.`Books` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_fp`.`CheckOut_History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_fp`.`CheckOut_History` ;

CREATE TABLE IF NOT EXISTS `library_fp`.`CheckOut_History` (
  `CheckOut_Date` DATE NOT NULL,
  `borrower_id` INT NOT NULL,
  `Barcode` INT NOT NULL,
  `Due_date` DATE NULL,
  `Return_Status` VARCHAR(3) NOT NULL,
  CONSTRAINT checkout_pk PRIMARY KEY (`CheckOut_Date`, `borrower_id`, `Barcode`),
  INDEX `borrower_id_idx` (`borrower_id` ASC),
  INDEX `Barcode_idx` (`Barcode` ASC),
  CONSTRAINT borrowerid_fk
    FOREIGN KEY (`borrower_id`)
    REFERENCES `library_fp`.`Borrowers` (`Borrower_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT barcode_fk
    FOREIGN KEY (`Barcode`)
    REFERENCES `library_fp`.`Barcodes` (`barcode`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_fp`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_fp`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `library_fp`.`Schedule` (
  `Day` VARCHAR(45) NOT NULL,
  `start_hour` TIME(2) NOT NULL,
  `end_hour` TIME(2) NOT NULL,
  `LibrarianID` INT NOT NULL,
  CONSTRAINT schedule_pk PRIMARY KEY (`Day`, `start_hour`, `end_hour`, `LibrarianID`),
  INDEX `day_idx` (`Day` ASC),
  INDEX `start_hour_idx` (`start_hour` ASC),
  CONSTRAINT lib_id_fk
    FOREIGN KEY (`LibrarianID`)
    REFERENCES `library_fp`.`Librarians` (`LibrarianID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_fp`.`Authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library_fp`.`Authors` ;

CREATE TABLE IF NOT EXISTS `library_fp`.`Authors` (
  `ISBN` CHAR(13) NOT NULL,
  `author_last_name` VARCHAR(45) NOT NULL,
  `author_first_name` VARCHAR(45) NOT NULL,
  CONSTRAINT authors_fk PRIMARY KEY (`ISBN`, `author_last_name`,  `author_first_name`),
  CONSTRAINT isbn_fk_2
    FOREIGN KEY (`ISBN`)
    REFERENCES `library_fp`.`Books` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
